#!/usr/bin/env node
/**
 * Exports the compiled ABIs into `@chain-drift/shared` as `as const` literals.
 *
 * viem infers argument and return types from the ABI, so the frontend and the
 * recorder get end-to-end typing from the Solidity source with no codegen step
 * beyond this one. Run via `pnpm --filter @chain-drift/contracts build`.
 */

import {readFileSync, writeFileSync, mkdirSync} from "node:fs";
import {dirname, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsRoot = resolve(here, "..");
const outDir = resolve(contractsRoot, "../shared/src/abis");

/** Contract name -> exported const name. */
const CONTRACTS = {
  DriftToken: "driftTokenAbi",
  CarNFT: "carNftAbi",
  RaceEscrow: "raceEscrowAbi",
  Leaderboard: "leaderboardAbi",
};

mkdirSync(outDir, {recursive: true});

const indexLines = [
  "// Generated by packages/contracts/scripts/export-abis.mjs — do not edit by hand.",
  "",
];

for (const [contract, exportName] of Object.entries(CONTRACTS)) {
  const artifactPath = resolve(contractsRoot, `out/${contract}.sol/${contract}.json`);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  } catch {
    console.error(`Missing artifact for ${contract} — run \`forge build\` first.`);
    process.exit(1);
  }

  const file = [
    "// Generated by packages/contracts/scripts/export-abis.mjs — do not edit by hand.",
    "",
    `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    "",
  ].join("\n");

  writeFileSync(resolve(outDir, `${contract}.ts`), file);
  indexLines.push(`export {${exportName}} from "./${contract}";`);
  console.log(`  ${contract} -> shared/src/abis/${contract}.ts`);
}

indexLines.push("");
writeFileSync(resolve(outDir, "index.ts"), indexLines.join("\n"));
console.log(`\nExported ${Object.keys(CONTRACTS).length} ABIs to ${outDir}`);
