// AUTO-GENERATED by scripts/pin-collection.mjs — do not edit manually.
import type { CarRarity } from "@chain-drift/shared";

export interface CollectionManifestEntry {
  model:      string;
  image:      string;
  rarity:     CarRarity;
  attributes: { trait_type: string; value: string }[];
}

export const COLLECTION_MANIFEST: Record<string, CollectionManifestEntry> = {
  "1": {
    "model": "https://ipfs.io/ipfs/bafybeifn6lrmsdbeoxd42zm4i35m27nztarpmj6jzsenoklrfpec3t2zqa",
    "image": "https://ipfs.io/ipfs/bafybeiempi5yg7v2alsa6okrnn3mljcp2z54kvkb57rrokz2latierdhtq",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "2": {
    "model": "https://ipfs.io/ipfs/bafybeif3swbsj7j4kkkvzhwdbdcmcsm62tp42bho25uuo7rq3ff7xcgih4",
    "image": "https://ipfs.io/ipfs/bafybeibyby3ukwgzqw3e2ik5lu3tbkao42yhnxqmuikgjadpfvridxxyr4",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "3": {
    "model": "https://ipfs.io/ipfs/bafybeigc2s6hgmt5oyeqr7zxwtjfais7fbesylzigdm25sn2ugdn3wrbdi",
    "image": "https://ipfs.io/ipfs/bafybeif2vwyck46lphsp62tzaqkcgkhxg2dlkmyh7hmiyqfp3zllahqet4",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "4": {
    "model": "https://ipfs.io/ipfs/bafybeihqfl3rdjbxo4ceewaxjgrn3ywltsut5d6h2jtiras4rjqfaz7i3i",
    "image": "https://ipfs.io/ipfs/bafybeiazs6bkksfdkerkczaekkaif6gll3ao4volagpj43o7bzr7bhfwza",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "5": {
    "model": "https://ipfs.io/ipfs/bafybeifmj5u4u2ibdgzrgry4smj4zfdkubw34v7gmedy2nl62c377c5s2i",
    "image": "https://ipfs.io/ipfs/bafybeid3rf6xel2lueuu2jkxgqcjh3b6a3ughqii4324mvq4oo6h7u2h6u",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "6": {
    "model": "https://ipfs.io/ipfs/bafybeidazy6togjolhne66v4ahcst3kljdxtivsr37fqb7xxg6uughifzi",
    "image": "https://ipfs.io/ipfs/bafybeig3xcyg7hlxeyomo3dte2xtw2jfjduwbcc3335rszorzjwnlvwiem",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "7": {
    "model": "https://ipfs.io/ipfs/bafybeibecbpqqqiantpe6eq626jfhnznikvorxji2rdicol343gp4b24xa",
    "image": "https://ipfs.io/ipfs/bafybeigx4qdxq4uwx54t4wz4gwmh3gul23337d2wbigmkvn7lw7htfbwxm",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "8": {
    "model": "https://ipfs.io/ipfs/bafybeidikzaubud7zzqwupu4sgfx4z5gkizc4jr23ntbnygt7rledttmwy",
    "image": "https://ipfs.io/ipfs/bafybeieiesgclpzn4gycvqipxu5qfwwzmjn7izqi4xd5lfpjjxktj3gwg4",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "9": {
    "model": "https://ipfs.io/ipfs/bafybeifkqwlocimsb3ryvy3lwqhoq25yhd6yu5hqusgnramvmkcexccpiy",
    "image": "https://ipfs.io/ipfs/bafybeigz3a2ndxnqpbdhquoxfpbnfr7aywhb4ki4w7nbondaur2aazhk4e",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Rare"
      }
    ]
  },
  "10": {
    "model": "https://ipfs.io/ipfs/bafybeib56bj7hweijl26i5l6b47wk4rj7jprsp6jcshn47yfu52n4nfija",
    "image": "https://ipfs.io/ipfs/bafybeigbg5hqoiazpiy75cwrfhxgggssrtu637dm3nphaxhnspvgdvtkpa",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "11": {
    "model": "https://ipfs.io/ipfs/bafybeidhvxw6tfkibesqjkcxkhqn7kicfsv2w5owgkq3x3mfczroxlfyvq",
    "image": "https://ipfs.io/ipfs/bafybeig6rl4gspvwqy7g6fssugsltxxn4bz4abnglegaskpusypf2lt2zi",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "12": {
    "model": "https://ipfs.io/ipfs/bafybeihsafotoxvay4i27stqdcgnwgyrjjumt37wwbjyzih3z7qlzqpswe",
    "image": "https://ipfs.io/ipfs/bafybeihwmidzf7dcq4ud4gvlebqbvgc7pbeyvlvl5mla24xma3hpmguvse",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "13": {
    "model": "https://ipfs.io/ipfs/bafybeiernnctsq25jtobo52b4v54gqj7z3ef6wf2gxzkl6v4wkyeisut4i",
    "image": "https://ipfs.io/ipfs/bafybeieblyzvpja6zywjaw4dchbhzgxjmor2xv5gffwbv47ycskssjjvdm",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "14": {
    "model": "https://ipfs.io/ipfs/bafybeieaiwfult7jsng2jh2gmjddvmt3jcedtsrih3lt3en5mmro2x3t3u",
    "image": "https://ipfs.io/ipfs/bafybeifvjfaxbsylb73ettpvbevodwz5vcitym7y3bowth4h65iwwcjmyi",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "15": {
    "model": "https://ipfs.io/ipfs/bafybeicy7qdunvvzm7a64pw7f2rh5rprgf7pesz4m6h7yhcya45ngvj5ve",
    "image": "https://ipfs.io/ipfs/bafybeiga4zelwhrxrxm55qxeqxh4rpyfwp323cnvmnmc57z4qrzwfui3vy",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "16": {
    "model": "https://ipfs.io/ipfs/bafybeibxoqdilkaxyjxcwphjimeet37stkma2jnhnxevbpphb3bjmbtfay",
    "image": "https://ipfs.io/ipfs/bafybeifu5zxzc335q5nkd2k34pqsxiz4dj2k6l6aosghq5wfvojxhpytdu",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "17": {
    "model": "https://ipfs.io/ipfs/bafybeidkzh4nyb5fvef4xzjcnj3zgju5hfcmczf4j3y6ucjmkuiv5wlqsq",
    "image": "https://ipfs.io/ipfs/bafybeihhhyi6dkknomrfi2gibjxihvh6i2jfq4p4bs5zcfxf54tngim37q",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "18": {
    "model": "https://ipfs.io/ipfs/bafybeidac65a3cpmb7ratrft76c7vdaxbti7p6byh43ptwzm5pejosy3e4",
    "image": "https://ipfs.io/ipfs/bafybeiajgprtb5aw2yp2nk6io6aw376aycyng3v5thmdgdwaf3rnje7axy",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Rare"
      }
    ]
  },
  "19": {
    "model": "https://ipfs.io/ipfs/bafybeih5vvghluplnqfjp5sxi5a5pyolpodykbmvd5vngeqtpxegoqyff4",
    "image": "https://ipfs.io/ipfs/bafybeigw3v6x73b24x3cfxiezwabmuli7ahwbuwztwvuhc73thfk6oyzna",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "20": {
    "model": "https://ipfs.io/ipfs/bafybeicfuhf5a2chrv4q62vvrgndwtphivmx4t5zflvzbsjch4ftiltiuu",
    "image": "https://ipfs.io/ipfs/bafybeia66jff5c44kb4nhaymdlopc63vcbmuosjxbo5y23fmqr6iyndrea",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "21": {
    "model": "https://ipfs.io/ipfs/bafybeihq6xmw47bokwh2slynven4gpb4osf6stdpfvp4otcrivwnbewpd4",
    "image": "https://ipfs.io/ipfs/bafybeibve6dufqkff4jndsqg4bxi6jnfni6uajxukyjf3wg6d7ief2woom",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "22": {
    "model": "https://ipfs.io/ipfs/bafybeicf3bruew6wnvbjek3nwlymkn5afqwtzfgeyljepjs2gm3wh6ed3y",
    "image": "https://ipfs.io/ipfs/bafybeicxzfmy7ol4rkh4ucnjpgv5tf7phwxezhzi267z35not2bwh34vva",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "23": {
    "model": "https://ipfs.io/ipfs/bafybeiccocjoos2cwu4o7irq5w35kvil7rnuuix42wp52ch5m3yn2ddcye",
    "image": "https://ipfs.io/ipfs/bafybeianboq2jvl5nrlfzw3gzrg5b4hvrm4q6sy7l32527y6k3hk5gkpri",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "24": {
    "model": "https://ipfs.io/ipfs/bafybeif26dlyoir6ve64objw4jaqj3jdpivdxb73xozyjdtqk474lcag7m",
    "image": "https://ipfs.io/ipfs/bafybeige666lzzpzmyftad76moakye2jxpbb7mmj34zlv6p75fimt6u4uy",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "25": {
    "model": "https://ipfs.io/ipfs/bafybeidyjtluhf6wjmkazvi7sryxezpaq4w66us46cvplt7up5v56cciju",
    "image": "https://ipfs.io/ipfs/bafybeidcezdiebkb7gfainkcuo7cyomtd575ksypf2isw3asbi4kxix24e",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "26": {
    "model": "https://ipfs.io/ipfs/bafybeighmfe4ksiijyt2vvefwnpcns2t2p7wppbofwb4ltvnf4t2fjzc3m",
    "image": "https://ipfs.io/ipfs/bafybeibjejyuzf44lfrv2siou3qf4t2x7m37l53odkpvfphls67qd57qbu",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "27": {
    "model": "https://ipfs.io/ipfs/bafybeibe2jctu3hy7qn7lqk5i3jbkb4q2hs7e7b77fisunnvwrt2rkkmay",
    "image": "https://ipfs.io/ipfs/bafybeigyb4f7odq5el3jynitmjnqwwod4hequ3h7rari2bh4qojcqfijou",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Rare"
      }
    ]
  },
  "28": {
    "model": "https://ipfs.io/ipfs/bafybeihpholwf2mkvi3t5iislxphzck6f5pnlns2lg5kao7oppsc5lediq",
    "image": "https://ipfs.io/ipfs/bafybeidcatx447n6fce2fv4jmlpt76zj4jutftmpdx6q6jj5hrsuzc5e2i",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "29": {
    "model": "https://ipfs.io/ipfs/bafybeie5vs3ivlw7zpg37aq6rlvuqcsu2xyo5jmwbk4xj4pjtmarclamwy",
    "image": "https://ipfs.io/ipfs/bafybeig6sz7fvikkwgg4xuutxylf2tztn54skkuvne5i5fgtygann3jw5m",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "30": {
    "model": "https://ipfs.io/ipfs/bafybeih7rpix6o32cjhluvsju4fgmlxjolwqoloru2px5wndzk4wrsf4sa",
    "image": "https://ipfs.io/ipfs/bafybeif6wyokaesffiuutbvkpygg26pjmubeugwuoemwto3whaieszmnrm",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "31": {
    "model": "https://ipfs.io/ipfs/bafybeiefze7mxlyh4fq2eun7gx7uo5jcfwt66j4xys7gw6bgwkxh2f7hu4",
    "image": "https://ipfs.io/ipfs/bafybeiccykhayqiwre7vrght5jh3qvmfhsh7dfg7w7upkdjaeug22wvtcu",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "32": {
    "model": "https://ipfs.io/ipfs/bafybeiea3wjkeaf7z4zh54knyisxrxsn7ovpubjeugqcqz3qwrfb7em5u4",
    "image": "https://ipfs.io/ipfs/bafybeife2kwr5g3jcwlp4aslgslberjvr72kushe7j7d5ck5a4onvogr6m",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "33": {
    "model": "https://ipfs.io/ipfs/bafybeibjvapvt55yplrd3girmwoveoxyzl2frk25rj2cz526l4jumt62qi",
    "image": "https://ipfs.io/ipfs/bafybeifhpu35jpu5tyzho5eboskk4kcvu2xctlbon7x65a72up2nblf2ye",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "34": {
    "model": "https://ipfs.io/ipfs/bafybeih42bpghf5jv5cw54ktejw4xmxxh2ucl7t7w23u4jod4v3bswr5ni",
    "image": "https://ipfs.io/ipfs/bafybeidaiylmcjootw64ssqr45zeb57nfp4mw6djhgaqsccgtals2ltdey",
    "rarity": "Legendary",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Legendary"
      }
    ]
  },
  "35": {
    "model": "https://ipfs.io/ipfs/bafybeid7hwz4v34rhms35guitvcfefpd633o7zpzvzvookdov5qgb3igri",
    "image": "https://ipfs.io/ipfs/bafybeibcsu35vty4xqgojgcrgji74jbcuykd2iir62e5ia5r6n2oeqy2bq",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "36": {
    "model": "https://ipfs.io/ipfs/bafybeie5d3tuyjudbxnmgxgprafuagz2kpsxeimboe24jdyvlwf462gmau",
    "image": "https://ipfs.io/ipfs/bafybeienvlkwqokohzngm75snigc74fcyuo7axfedm3xntvfyriltllhd4",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Rare"
      }
    ]
  },
  "37": {
    "model": "https://ipfs.io/ipfs/bafybeifftxpjge2p5g5ulqz2gcq3gxomyn7e42b4n2ipqkcikd2eveofsm",
    "image": "https://ipfs.io/ipfs/bafybeicptveuyj4w2ziqqmg2x7mddnc7tab3fluynahm5avbqn7o3wnvfq",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "38": {
    "model": "https://ipfs.io/ipfs/bafybeihxookkpkdtyo723bidybljzwvxvcidq32xng3ztbjnxj72g7z73e",
    "image": "https://ipfs.io/ipfs/bafybeigplz4bawsum6imoscviyxbjqusqjteepgmm2twipchnq3hepmpw4",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "39": {
    "model": "https://ipfs.io/ipfs/bafybeia6vpy2jwpgobi45zzx55jokgtegiryf36x6cpqodpm6h4nf2ns74",
    "image": "https://ipfs.io/ipfs/bafybeia7klr765hckmq5jaq6efbzaaezzlqifxplbc4hewfgstoinj2c5m",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "40": {
    "model": "https://ipfs.io/ipfs/bafybeib2k7zilop572dc2kgumgk7b2bcebswih3rwsz6k2xkcwz6kxd5ni",
    "image": "https://ipfs.io/ipfs/bafybeicnb6dr7s24iw7ancirryff7utbo5rrgivn53rtp3rx5t3mfsgj3i",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "41": {
    "model": "https://ipfs.io/ipfs/bafybeib4ff7enjolzuwkpyhrqlgptukrbj2yyhjlzd7dwpqzxajzawceqi",
    "image": "https://ipfs.io/ipfs/bafybeidvlsuelqkwfyhrwbck4f42q3uis7hxetvznqqmzqnrqcl646um7a",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "42": {
    "model": "https://ipfs.io/ipfs/bafybeichjnm7lbe2sijrkqxosdhc732tuqcds7lrnwreh4hg6hglxrnzgy",
    "image": "https://ipfs.io/ipfs/bafybeicw47l7y2aigmxvyo4ttkf4euc2wu5kb7y5ifejhg6cnhwfa4p7gq",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "43": {
    "model": "https://ipfs.io/ipfs/bafybeidyf2ybk7cvceqzxlg5rgxpsyfi22hrruemgao2235ctmai54r2yu",
    "image": "https://ipfs.io/ipfs/bafybeigtxfdubdixcuhinibcbgqcn3wqv5zbt56isxy2ehhafmk2tjuvfu",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "44": {
    "model": "https://ipfs.io/ipfs/bafybeibtrxub2jd5ki56c2l4x7pbd4xuv3n4mi4mt3tj26swaklqc6mose",
    "image": "https://ipfs.io/ipfs/bafybeifjueqqis7tfisdlsb27s27dk5otazipwcj5h63ojxrdwfbcetp6m",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "45": {
    "model": "https://ipfs.io/ipfs/bafybeici5sxijfvixcpobbet54t54guoxqzfjpxuj4ddmw2m6hvbkfbeaq",
    "image": "https://ipfs.io/ipfs/bafybeic5ww77pj7pj6qly72nlkskpwnifaw2fo7todncpgktbywsttqiau",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Rare"
      }
    ]
  },
  "46": {
    "model": "https://ipfs.io/ipfs/bafybeictxirmmodyivkhe5fniclch4grqsii5n4e5wogog6kmvw7svlaq4",
    "image": "https://ipfs.io/ipfs/bafybeibz7xrb6dakvi42gi7tfb5o643bouw7irw3jyichzhc7t4fzt2lg4",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "47": {
    "model": "https://ipfs.io/ipfs/bafybeicwfqnbo6ypkksr6g234ayumgo4f7im47d4x3pdyvz44zdawst5fq",
    "image": "https://ipfs.io/ipfs/bafybeih3qlld2pso7pn7oljll5asrknovpecgfj2aut4vsgc2dod52fdoq",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "48": {
    "model": "https://ipfs.io/ipfs/bafybeidrmgaezc4kk5judrmliif7zzg6x2ppgjh6doq2gij3huhr73h5le",
    "image": "https://ipfs.io/ipfs/bafkreib7hudqz5kaysohorhwt56eb6fvt2klpfawx3kh5bq6jfwo5xuwai",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "49": {
    "model": "https://ipfs.io/ipfs/bafybeift2bv7y2e5kq4jktkoovcwefgwa7xvvwamzchk6lknbayxf6h6tu",
    "image": "https://ipfs.io/ipfs/bafybeiag7rgiwog4vshhoxubhaibbavtwyp5fxbukck37j4iqehroj7cvq",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "50": {
    "model": "https://ipfs.io/ipfs/bafybeiad24p7ucixjd3t7dlk6brspnvollngtvv5jotee7vob7g5dudrqm",
    "image": "https://ipfs.io/ipfs/bafybeie46w46pwuywudlkfjdb3ubgax2xco6uvjlpmenu6vdenx3z57bre",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "51": {
    "model": "https://ipfs.io/ipfs/bafybeigadpjovcr43vt64bktkj2s7vlh2zwwblxxrdjptx4dp3elinbolu",
    "image": "https://ipfs.io/ipfs/bafybeiacvkvdkom35avr7xikryq5x4mulexfywjioxg5cvq4u2sbpekl3i",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "52": {
    "model": "https://ipfs.io/ipfs/bafybeidhdrzbyn5aglx2hapmmhkvr3zdlacpdp2uvmshugjmqio7d7vwpe",
    "image": "https://ipfs.io/ipfs/bafybeif55lfoxlgvxplhfexynbrmdm6x3copjtqtg7djupqlzw64hfsgxu",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "53": {
    "model": "https://ipfs.io/ipfs/bafybeido4ckdpwmyycsubfklhl3wjq4gbrimeeg7gqgvhgdec4uubsgscm",
    "image": "https://ipfs.io/ipfs/bafybeiews3nip53wyw23tijg5f2wdeszfwhafqcnkys6t6kys6tjn42qzu",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "54": {
    "model": "https://ipfs.io/ipfs/bafybeigk4cknd4l3emd6rkwfgvczwgcers23thzqbawclihqhwjli3vhzq",
    "image": "https://ipfs.io/ipfs/bafybeigfzklr35v43mb7ld3fcdttcgwhe2la5tfccsxj3kay7fn74o4pee",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Rare"
      }
    ]
  },
  "55": {
    "model": "https://ipfs.io/ipfs/bafybeihbck53vmab6rah25gccankrwoxwqf7km3o5jdyv52pslvi24yrfi",
    "image": "https://ipfs.io/ipfs/bafybeic6pysfcrgmrbazmewlipbk4cas3py4xptzwatyoj4ripp7h3hzau",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "56": {
    "model": "https://ipfs.io/ipfs/bafybeiefqzqitz5xjluppbppb3qhyx6feqaplhpqdoopbmwixyjqdn6hnm",
    "image": "https://ipfs.io/ipfs/bafybeicbot7bhtxuqprzqfbdbtgp63irfj7c5pejmfhbq56xtifh7qnk5u",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "57": {
    "model": "https://ipfs.io/ipfs/bafybeidzqtwzzalafhf6ubzlplky2afjtygoyym3cwwqfknbm4f5werg5q",
    "image": "https://ipfs.io/ipfs/bafybeifrnkiwmf5mzwvmfecpsjvosr4gwluzflriacku7zvftxs3dbczqi",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Retro Tuner"
      },
      {
        "trait_type": "Neon Color",
        "value": "purple"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "58": {
    "model": "https://ipfs.io/ipfs/bafybeiejy7zksignlvbstdqpfhvh3h27rliipfhjii3hzewwtsyuonpm34",
    "image": "https://ipfs.io/ipfs/bafybeicou6vul4tnxl4xfljangbfukeleoqfvkca3he3yuon2zxwxfs6fy",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Street Racer"
      },
      {
        "trait_type": "Neon Color",
        "value": "orange"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "59": {
    "model": "https://ipfs.io/ipfs/bafybeigxcql4ux6xztogbef2dw6tbtvxgurqr6i7kaqunwsxocrn2mcu7u",
    "image": "https://ipfs.io/ipfs/bafybeiaiuvqaisb3kbdgkaj3ws7osihftclonilmcpf6wqiaic4g3suavu",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber GT"
      },
      {
        "trait_type": "Neon Color",
        "value": "cyan"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  },
  "60": {
    "model": "https://ipfs.io/ipfs/bafybeibp4idmpcqhpnqhgi4lt4676gslfjg3tjcbkkqvluq3vjgpffhndq",
    "image": "https://ipfs.io/ipfs/bafybeid6eyyei5la7amhndpqaxric5rv2yhrzv25ia4mrwrcjjx4iuu5n4",
    "rarity": "Rare",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Drift Coupe"
      },
      {
        "trait_type": "Neon Color",
        "value": "pink"
      },
      {
        "trait_type": "Rarity",
        "value": "Uncommon"
      }
    ]
  },
  "61": {
    "model": "https://ipfs.io/ipfs/bafybeidz2w2h72u7gtirvgmu57cecocajnzdchak525ki4difw3dhrxqxq",
    "image": "https://ipfs.io/ipfs/bafybeibdqgsiyaan2fyglqwi34njjxa6atkwwabhcte7tfa5szahfxeiqi",
    "rarity": "Common",
    "attributes": [
      {
        "trait_type": "Archetype",
        "value": "Cyber Muscle"
      },
      {
        "trait_type": "Neon Color",
        "value": "lime"
      },
      {
        "trait_type": "Rarity",
        "value": "Common"
      }
    ]
  }
};

export function getCarManifest(tokenId: number): CollectionManifestEntry | null {
  return COLLECTION_MANIFEST[String(tokenId)] ?? null;
}
