// ─── IPFS Gateway Config ──────────────────────────────────────────────────
//
// The collection manifest stores absolute gateway URLs (auto-generated by
// scripts/pin-collection.mjs). Public gateways go down regularly, so every
// IPFS URL is re-resolved at runtime against an ordered gateway list and
// retried across the list until one answers.
//
// Override the list with VITE_IPFS_GATEWAYS (comma-separated, no trailing
// slash), e.g. a dedicated Pinata gateway:
//   VITE_IPFS_GATEWAYS=https://my-gw.mypinata.cloud/ipfs,https://dweb.link/ipfs

const DEFAULT_GATEWAYS = [
  "https://gateway.pinata.cloud/ipfs",
  "https://dweb.link/ipfs",
  "https://w3s.link/ipfs",
  "https://ipfs.io/ipfs",
];

export const IPFS_GATEWAYS: string[] = (() => {
  const raw = import.meta.env.VITE_IPFS_GATEWAYS as string | undefined;
  const list = raw
    ?.split(",")
    .map((s) => s.trim().replace(/\/+$/, ""))
    .filter(Boolean);
  return list?.length ? list : DEFAULT_GATEWAYS;
})();

// Per-request budget before falling through to the next gateway.
const GATEWAY_TIMEOUT_MS = 15_000;

// Once a gateway answers, prefer it for every later request in this session.
let preferredGateway: string | null = null;

/**
 * Extract the `<cid>[/path]` portion of an IPFS reference.
 * Accepts gateway URLs, `ipfs://` URIs, and bare CIDs.
 * Returns null for anything that isn't an IPFS reference.
 */
export function ipfsPath(url: string): string | null {
  const gatewayMatch = url.match(/\/ipfs\/(.+)$/);
  if (gatewayMatch) return gatewayMatch[1];
  if (url.startsWith("ipfs://")) return url.slice("ipfs://".length);
  if (/^(Qm[1-9A-HJ-NP-Za-km-z]{44}|b[a-z2-7]{58,})(\/.*)?$/.test(url)) return url;
  return null;
}

/** Gateways to try, most-likely-to-work first. */
function orderedGateways(): string[] {
  return preferredGateway
    ? [preferredGateway, ...IPFS_GATEWAYS.filter((g) => g !== preferredGateway)]
    : IPFS_GATEWAYS;
}

/** Every gateway URL for an IPFS reference, most-likely-to-work first. */
export function ipfsCandidates(url: string): string[] {
  const path = ipfsPath(url);
  if (!path) return [url];
  return orderedGateways().map((gw) => `${gw}/${path}`);
}

/** The single best URL for an IPFS reference (for <img>, links, etc.). */
export function resolveIpfs(url: string): string {
  return ipfsCandidates(url)[0];
}

/**
 * Fetch an IPFS resource, trying each gateway in turn until one responds.
 * Throws only when every gateway fails.
 */
export async function fetchIpfs(url: string): Promise<ArrayBuffer> {
  const path = ipfsPath(url);
  const attempts: { gateway: string | null; url: string }[] = path
    ? orderedGateways().map((gateway) => ({ gateway, url: `${gateway}/${path}` }))
    : [{ gateway: null, url }];

  const failures: string[] = [];

  for (const attempt of attempts) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), GATEWAY_TIMEOUT_MS);
    try {
      const res = await fetch(attempt.url, { signal: controller.signal });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const buffer = await res.arrayBuffer();
      if (attempt.gateway) preferredGateway = attempt.gateway;
      return buffer;
    } catch (err) {
      failures.push(`${attempt.url} (${(err as Error).message})`);
    } finally {
      clearTimeout(timer);
    }
  }

  throw new Error(`All IPFS gateways failed for ${url}:\n  ${failures.join("\n  ")}`);
}
